sudo: required
dist: trusty
os: linux
language: node_js
node_js:
  - "8"

cache:
  directories:
    - "node_modules"

before_deploy:
  - npm run build
  - git config user.email "ignacio@bloq.com"
  - git config user.name "Ignacio Anaya"
  - git add --force .nuxt
  - git commit -m 'Add .nuxt folder'

deploy:
  - provider: elasticbeanstalk
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    region: "sa-east-1"
    app: "metronome-explorer"
    env: "metronome-explorer-prod"
    bucket_name: "elasticbeanstalk-sa-east-1-869739316835"
    on:
      branch: master
  - provider: elasticbeanstalk
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    region: "sa-east-1"
    app: "metronome-explorer"
    env: "metronome-explorer-dev"
    bucket_name: "elasticbeanstalk-sa-east-1-869739316835"
    on:
      branch: develop